name: EvoPlugin
author: Palmus_
main: fr.palmus.plugin.EvoPlugin
version: 3.0.0
api-version: 1.18
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.0.6
depend:
  - CoreProtect
  - LuckPerms
  - WorldGuard
  - WorldEdit
  - Votifier
commands:
  exp:
    description: Intéragir avec le module d'exp
    default: op
  farmzone:
    description: Intéragir avec le module farmlands
    default: op
  rtp:
    description: Téléporte le joueur aléatoirement
  money:
    description: Accéder au module d'economie
  periode:
    description: Accéder aux information à propos des périodes
    aliases:
      - info
      - infos
      - periodes
      - period
  bank:
    description: Montre l'argent d'un joueur
  bienvenue:
    description: Souhaiter la bienvenue à un joueur
    aliases:
      - b
      - w
      - welcome
  info:
    description: Montre les infos d'un joueur !
  crate:
    description: Permet de créer/modifier une crate.
  lobby:
    description: teleport you to the spawn
    aliases:
      - spawn
      - hub
permissions:
  evoplugin.*:
    description: Administrator permissions.
    children:
      evoplugin.mod: true
      farmzone.set: true
      shipbattle.setup: true

  farmzone.set:
    description: Defined farmzone.
    default: false

  evoplugin.exp_mod:
    description: Access to exp moderation commands
    default: op


