name: EvoPlugin
author: Palmus_
main: fr.palmus.plugin.EvoPlugin
version: 2.2.3
api-version: 1.18
depend:
  - CoreProtect
  - LuckPerms
  - WorldGuard
  - WorldEdit
commands:
  exp:
    description: Intéragir avec le module d'exp
    default: op
  farmzone:
    description: Intéragir avec le module farmlands
    default: op
  rtp:
    description: Téléporte le joueur aléatoirement
  money:
    description: Accéder au module d'economie
  periode:
    description: Accéder aux information à propos des périodes
    aliases:
      - info
      - infos
      - periodes
      - period

permissions:
  evoplugin.*:
    description: Administrator permissions.
    children:
      evoplugin.mod: true
      farmzone.set: true
      shipbattle.setup: true

  farmzone.set:
    description: Defined farmzone.
    default: false

  evoplugin.exp_mod:
    description: Access to exp moderation commands
    default: op

  evoplugin.econ_mod:
    description: Jog a ShipBattle plugin setup parancsaihoz.
    default: op

