name: EvoPlugin
author: Palmus_
main: fr.palmus.plugin.Main
version: 1.0
api-version: 1.18
depend:
  - LuckPerms
  - WorldGuard
  - WorldEdit
commands:
  exp:
    description: Intéragir avec le plugin d'exp
    default: op
  farmzone:
  rtp:
    description: Téléporte le joueur aléatoirement

